---
title: "Create Table 1 in PDF (One way to include header for armed conflict)"
format: pdf
---

```{r}
#| label: load-packages
#| include: false
source("../.Rprofile")
```

```{r}
#| echo: FALSE
conflict <- read.csv(here("data", "analytical", "finaldata.csv"), header = TRUE)
baseline <- conflict %>%
  dplyr::filter(year == 2000)
baseline$armconf1f <- factor(baseline$armconf1, levels = c(0,1), labels = c("No", "Yes"))
baseline$droughtf <- factor(baseline$drought, levels = c(0,1), labels = c("No", "Yes"))
baseline$earthquakef <- factor(baseline$earthquake, levels = c(0,1), labels = c("No", "Yes"))
baseline$OECDf <- factor(baseline$OECD, levels = c(0,1), labels = c("No", "Yes"))

label(baseline$gdp1000)       <- "GDP per capita"
label(baseline$OECD)          <- "OECD member"
label(baseline$popdens)       <- "Population density"
label(baseline$urban)         <- "Urban residence"
label(baseline$agedep)        <- "Age dependency ratio"
label(baseline$male_edu)      <- "Male education"
label(baseline$temp)          <- "Mean annual temperature"
label(baseline$rainfall1000)  <- "Mean annual rain fall"
label(baseline$earthquakef)   <- "Earthquake"
label(baseline$earthquake)    <- "Earthquake"
label(baseline$droughtf)      <- "Drought"
label(baseline$drought)       <- "Drought"
label(baseline$armconf1f)     <- "Armed conflict"
label(baseline$totdeath)      <- "Total number of deaths"
label(baseline$matmor)        <- "Maternal mortality"
label(baseline$infmor)        <- "Infant mortality"
label(baseline$neomor)        <- "Neonatal mortality"
label(baseline$un5mor)        <- "Under 5 mortality"
label(baseline$armconf1f)     <- "Armed conflict"


units(baseline$gdp1000)       <- "USD"
#units(baseline$popdens) <- "% of population living in a density of >1,000 people/km^2"


mytable1 <- 
table1(~ gdp1000 + OECDf + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquakef + droughtf| armconf1f, data = baseline,
        render.continuous = c(.="Median [Min, Max]"),
       overall=c(left="Total"))
```


```{r}
#| echo: FALSE
t1kable(mytable1) %>%
  add_header_above(c(" "=2, "Armed conflict in 2000" = 2))
```


```{r}
#| echo: FALSE
ft1 <- t1flex(mytable1) 
add_header_row(ft1,
  values = c("", "Armed conflict in 2000"),
  colwidths = c(2, 2))
```



